sudo: required
services:
  - docker

before_install:
  - docker build -t gsylverman/multi-client -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true gsylverman/multi-client npm test

after_success:
  - docker build -t gsylverman/multi-client ./client
  - docker build -t gsylverman/multi-nginx ./nginx
  - docker build -t gsylverman/multi-server ./server
  - docker build -t gsylverman/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push gsylverman/multi-client
  - docker push gsylverman/multi-nginx
  - docker push gsylverman/multi-server
  - docker push gsylverman/multi-worker