apiVersion: v1
kind: Pod
metadata:
  name: client-pod
  labels:
    app: web
spec:
  containers:
    - name: client
      image: gsylverman/multi-cnt1-app
      ports:
        - containerPort: 3000
      imagePullPolicy: IfNotPresent
  restartPolicy: Always
