apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
  labels:
    app: web
spec:
  replicas: 1
  template:
    metadata:
      name: client
      labels:
        app: web
    spec:
      containers:
        - name: web
          image: gsylverman/multi-cnt1-app
          ports:
            - containerPort: 3000
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
  selector:
    matchLabels:
      app: web
